# Generated by Django 2.0.4 on 2018-04-07 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 49, 32, 416685)),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 49, 32, 416717)),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 49, 32, 424818)),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 49, 32, 424845)),
        ),
    ]
