# Generated by Django 2.0.4 on 2018-04-07 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_auto_20180407_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businesstype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='businesstype',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesstype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
