# Generated by Django 2.0.4 on 2018-04-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_auto_20180407_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('total_vacancy', models.IntegerField()),
                ('job_nature', models.CharField(max_length=150)),
                ('educational_requirement', models.TextField()),
                ('job_requirement', models.TextField()),
                ('job_location', models.TextField()),
                ('company_benefit', models.TextField()),
                ('year_of_experience', models.TextField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('skill_sets', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('deadline', models.DateField()),
                ('is_published', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.Company')),
            ],
        ),
    ]
