# Generated by Django 2.0.3 on 2018-04-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_auto_20180407_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
    ]
