# Generated by Django 2.0.4 on 2018-04-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_contract'),
        ('job_portal', '0006_faq'),
    ]

    operations = [
    ]
