# Generated by Django 2.0.4 on 2018-04-10 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_merge_20180408_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=150)),
                ('mothers_name', models.CharField(max_length=150)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('picture', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=120)),
                ('national_id', models.CharField(max_length=120)),
                ('skills', models.TextField()),
                ('religion', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=200)),
                ('session', models.CharField(max_length=50)),
                ('passing_year', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=120)),
                ('board', models.CharField(max_length=120)),
                ('university', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 10, 20, 37, 0, 816197, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
