# Generated by Django 2.0.4 on 2018-04-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_auto_20180410_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_salary', models.IntegerField()),
                ('cover_letter', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.Employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.Job')),
            ],
        ),
    ]
