# Generated by Django 2.0.4 on 2018-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_employeejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hobby',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
