# Generated by Django 2.0.4 on 2018-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_add_user_id_to_emplyee'),
    ]

    operations = [

        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_established',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='year_of_experience',
            field=models.CharField(max_length=50),
        ),
    ]
