# Generated by Django 2.0.4 on 2018-04-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0013_add_date_of_birth_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', upload_to='', width_field='width'),
        ),
        migrations.AddField(
            model_name='employee',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
