# Generated by Django 2.0.4 on 2018-04-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0014_add_picture_to_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='height',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='width',
        ),
    ]
